### ISSUE TITLE
Jailbar Fix

### ISSUE THREAD

**Issue by L10N37** [consolesunleashed/sega-master-system-divide-by-three-jailbar-fix#1]
Hey there,

Using SI5351 to create all the clocks used on the board using a single PLL in software, should keep them all in sync. 25Mhz is the clock (by default, connected to the IC) so the software PLL is a multiplication of that clock.

You shouldn't need to divide any clocks. The above method is simply producing all the clocks from the same master clock. It's the same, but different. (well in essence, you are dividing a clock, but it's done in software)

**Comment by L10N37** [comment]
https://www.smspower.org/Development/ClockRate

```
In NTSC systems, the master clock crystal is rated as 53.6931MHz. This is divided by 15 to give 3579540Hz, used as the system clock (for the CPU, PSG and other devices) and also for the RF encoder as the [Chrominance](https://en.wikipedia.org/wiki/Chrominance) subcarrier frequency. Because this latter value is officially set to 315/88 MHz, the clock value of 3579545Hz is commonly used although the difference is negligible.

PAL systems have a master clock crystal rated as 53.2034MHz, which is again divided by 15 to give 3546893Hz as the system clock. The PAL RF chrominance subcarrier frequency of 4.43361875MHz (precisely) is obtained by dividing it by 12. Applying the same reverse logic as before yields a "true" system clock of 3546895Hz, again a negligible difference.
```

So we only need 2 of the 3 clock outputs the IC offers. System clock and the sub carriers.

You could get a true NTSC/ PAL system if you went all out with the encoders PAL/NTSC leg, as well as the VDP's so they all agreed on toggle. 

The hard part is the software sucks, you need to basically work out all the maths on paper/ calculator and then check with a scope. Trial and error as well. What you work out won't be the exact result on the scope read out.

The clock maths stuff is here:
https://learn.adafruit.com/adafruit-si5351-clock-generator-breakout/wiring-and-test#set-up-the-pll-2460686

From memory the French system uses a different clock?  its somewhere around abouts though.

edit: i see there's a division of that clock for the VDP as well, so you would need all 3 outputs.

**Comment by consolesunleashed** [comment]
Cheers. Will have a look at this, but software isn't my thing. I've already made a true NTSC and PAL console with a DFO plus my RGB Encoder Switcher. This creates all the correct clocks and switches everything at the same time. I am currently just trying to get a divider working using discrete components. Just a simple divide by three circuit which will combine with my RGB Encoder Switcher to provide all the correct switching for the system. Should be very simple.

**Comment by L10N37** [comment]
8 bit microcontrollers don't take long to pick up :) I have a spare clock gen board I can have a peak into it and leave the board design up to you. I did see Leah Rowe working on this a few years back but he seems to have disappeared off the internet. I'll get the clocks produced sometime when I get a chance and see if I can implement either button combo or reset counter to flick modes ? when I do I'll pop you a message  (maybe powering the system on while holding pause would be an easy way to set a mode )
